### ISSUE TITLE
Take control of the preview image on platforms like FB, Twitter, Slack, messenger, ...

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/2019.indieweb.org#36]
When I shared https://2019.indieweb.org/summit with a friend I noticed the link preview was @aaronpk's avatar. We should probably add an `og:image` meta tag with the IWC logo -- or at least include a high resolution version of the logo somewhere near the top of the page (before the RSVPs), which is more likely to be inferred as the image for link previews.

Reference https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2F2019.indieweb.org%2Fsummit

**Comment by martymcguire** [comment]
Renaming b/c the `og:image` in the name of this issue caused contention and we care more about the outcome than the methodology to get there.

The issue is: many services want to make an image preview for a given URL. They use very inconsistent algorithms for this. We have seen some undesirable things like using a single attendee or speaker's image as the "preview" image for the summit event.

Some options include:

- `og:image` is metacrap but very common.
- Requiring a large hero image might work for most.
- Maybe a combo.

We should start recording when this happens and where, so we can test.
